phuthuproject/apps/chuyenthue/urls.py
from django.conf.urls import url
from . import views
from . import views
from . views import inphieu
urlpatterns = [
    url(r'^chonphieuin/$', views.chonphieuin, name='chonphieuin'),
    url(r'^inphieu/$', inphieu.as_view()),
    #url(r'^admin/tpc/(?P<pcid>\d+)/$', views.admin_tpc_detail,name='admin_tpc_detail'),
    url(r'^admin/tpc/(?P<pcid>\d+)/pdf/$', views.admin_tpc_pdf,name='admin_tpc_pdf'),
	#url(r'^add_chuyenthue/$', views_congtac.add_congtac, name='add_congtac'),
    #url(r'^tim_chuyenthue/$', views_congtac.tim_congtac.as_view(), name='tim_congtac'),
]

phuthuproject/apps/myapp/urls.py
from django.conf.urls import url
from . import views
from . import views_congtac
from . views_congtac import GeneratePdf
urlpatterns = [
    url(r'^add_congtac/$', views_congtac.add_congtac, name='add_congtac'),
    url(r'^tim_congtac/$', views_congtac.tim_congtac.as_view(), name='tim_congtac'),
    url(r'^thu/$', views_congtac.thu.as_view(), name='thu'),
    #url(r'^pdf/$', views_congtac.GeneratePdf.as_view(), name='GeneratePdf'),
	url(r'^pdf/$', GeneratePdf.as_view()),
]

phuthuproject/phuthuproject/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from apps.myapp.views import index
#from django.conf import settings
#from django.conf.urls.static import static
#admin.autodiscover()
urlpatterns = [
    #url(r'^admin/', admin.site.urls),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^$',index),
	url(r'^myapp/', include('apps.myapp.urls', namespace='myapp')),
	url(r'^chuyenthue/', include('apps.chuyenthue.urls', namespace='chuyenthue')),
]

phuthuproject/apps/chuyenthue/models.py
from django.db import models
from multiselectfield import MultiSelectField
# Create your models here.
class TPc(models.Model):
    #pcid = models.AutoField(primary_key= True)
    pcid = models.AutoField(primary_key=True)
    so = models.CharField(max_length=50, blank=True, null=True)
    soin = models.CharField(max_length=50, blank=True, null=True)
    ngaychuyen = models.DateTimeField(blank=True, null=True)
    hovaten = models.CharField(max_length=250, blank=True, null=True)
    diachi = models.CharField(max_length=250, blank=True, null=True)
    thuadatso = models.CharField(max_length=250, blank=True, null=True)
    tobando = models.CharField(max_length=250, blank=True, null=True)
    dcthuadat = models.CharField(max_length=250, blank=True, null=True)
    loaiduong = models.CharField(max_length=250, blank=True, null=True)
    hangdat = models.CharField(max_length=50, blank=True, null=True)
    vitri = models.CharField(max_length=255, blank=True, null=True)
    loaidat = models.CharField(max_length=250, blank=True, null=True)
    mdsudung = models.CharField(max_length=250, blank=True, null=True)
    thsudung = models.CharField(max_length=50, blank=True, null=True)
    odlaudai = models.CharField(max_length=50, blank=True, null=True)
    cthtungay = models.CharField(max_length=50, blank=True, null=True)
    cthdenngay = models.CharField(max_length=50, blank=True, null=True)
    dientich = models.CharField(max_length=250, blank=True, null=True)
    dtnt = models.CharField(max_length=250, blank=True, null=True)
    dtnttronghm = models.CharField(max_length=250, blank=True, null=True)
    dtnttrenhm = models.CharField(max_length=250, blank=True, null=True)
    dtdt = models.CharField(max_length=250, blank=True, null=True)
    dtdtsdr = models.CharField(max_length=250, blank=True, null=True)
    dtdtsdc = models.CharField(max_length=250, blank=True, null=True)
    nguongoc = models.CharField(max_length=250, blank=True, null=True)
    thoidiemsdd = models.CharField(max_length=250, blank=True, null=True)
    noptien100 = models.NullBooleanField()
    noptien50 = models.NullBooleanField()
    noptien50clld = models.NullBooleanField()
    noptienclld = models.NullBooleanField()
    capnha = models.CharField(max_length=255, blank=True, null=True)
    dtsannha = models.CharField(max_length=250, blank=True, null=True)
    sotangnha = models.CharField(max_length=255, blank=True, null=True)
    nguongocnha = models.CharField(max_length=255, blank=True, null=True)
    ngayhoancong = models.CharField(max_length=50, blank=True, null=True)
    doituongkpn = models.CharField(max_length=255, blank=True, null=True)
    doitongbtth = models.CharField(max_length=255, blank=True, null=True)
    nhanvien = models.CharField(max_length=100, blank=True, null=True)
    loaihoso = models.CharField(max_length=255, blank=True, null=True)
    def __unicode__(self):
        return self.hovaten
    def __str__(self):
        return self.hovaten
    class Meta:
        managed = False
        db_table = 't_pc'

phuthuproject/apps/myapp/models.py
from django.db import models

# Create your models here.
class Congtac(models.Model):
    id = models.AutoField(primary_key=True)
    ten = models.CharField(max_length=50,blank=True, null=True)
    diachi = models.CharField(max_length=50, blank=True, null=True)
    congtac = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
       # db_schema = APP_SCHEMA
        managed = False
        db_table = 'congtac'

phuthuproject/apps/chuyenthue/forms.py
from django import forms
class SelectFileForm(forms.Form):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)
    file = forms.FileField()

phuthuproject/apps/myapp/forms.py
from django import forms
from apps.myapp.models import Congtac
from django.core.exceptions import ValidationError
#from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify
from django.forms import CharField
from django.core import validators
from django import forms
from django.core.validators import validate_email

class CongtacForm(forms.ModelForm):
    class Meta:
        model = Congtac
        fields = ['id','ten', 'diachi', 'congtac']
class SearchForm(forms.Form):
   hovaten = forms.CharField(label='Nhập họ tên tìm kiếm',widget = forms.TextInput(attrs={'size': 32, 'class':'formcontrol'}))

phuthuproject/apps/chuyenthue/views.py
from django.shortcuts import render
from apps.chuyenthue.models import TPc
from .tables import CongtacTable
from django.http import HttpResponse
from django.views.generic import View
from django.template.loader import get_template
from .utils import render_to_pdf #created in step 4
# Create your views here.
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404

"""
@staff_member_required
def admin_tpc_detail(request, pcid):
	tpc = get_object_or_404(TPc, id=pcid)
	return render(request,'detail.html',{'tpc': tpc})
"""
from django.conf import settings 
from django.http import HttpResponse
from django.template.loader import render_to_string
import weasyprint
@staff_member_required
def admin_tpc_pdf(request, pcid):
		tpc = get_object_or_404(TPc, id=pcid)
		html = render_to_string('pdf.html',{'tpc': tpc})
		response = HttpResponse(content_type='application/pdf')
		response['Content-Disposition'] = 'filename=\"tpc_{}.pdf"'.format(tpc.id)
		weasyprint.HTML(string=html).write_pdf(response,stylesheets=[weasyprint.CSS(settings.STATIC_ROOT + 'css/pdf.css')])
		return response
def chonphieuin(request):
    dk = CongtacTable(TPc.objects.all())
    return render(request, 'thu.html', {'table_ketqua': dk})
class inphieu(View):
    def get(self, request, *args, **kwargs):
        template = get_template('inphieu.html')
        context = {
              'today': '04/11/2017',
              'amount': 39.99,
             'customer_name': 'Cooper Mann',
             'order_id': 1233434,
        }
        html = template.render(context)
        pdf = render_to_pdf('inphieu.html', context )
        if pdf:
           return HttpResponse(pdf, content_type='application/pdf')
        return HttpResponse ("not fount")

phuthuproject/apps/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index (request):
    return HttpResponse('<h1>  Phòng Tài nguyên và Môi trường Cái Răng</h1>')

phuthuproject/apps/chuyenthue/templates/chonphieuin.html
{% load render_table from django_tables2 %}
{% load static %}
<!doctype html>
<html lang="vi">
    <head>
        <meta charset="UTF-8">
        <title>Ví dụ Tabs trong AngularJS - Freetuts.net</title>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.min.js"></script>
          <link href="{% static 'css/timkiem.css' %}" rel="stylesheet" media="screen"/>
		 <link href="{% static 'css/forms.css' %}" rel="stylesheet" media="screen">
         <link href="{% static 'css/screen.css' %}" rel="stylesheet" media="screen"/>
         <link href="{% static 'css/thu.css' %}" rel="stylesheet" media="screen"/>
	     <meta http-equiv= "Content-type" content="text/html"; charset="UTF-8">

        <script language="javascript" src="{% static  "djng/js/angular.min.js" %}"> </script>

        <script language="javascript" src="{% static  "djng/thu.js" %}"></script>
		
		<style>
            *{margin:0;padding:0}
            body{margin:20px;}
            .tabs-heading{
                padding: 20px 20px 0px 20px;
                height: 30px;
                border: solid 1px gray;
                border-radius: 5px 5px 0px 0px;
                background-color: #cae8fd;
            }
            .tabs-heading a{
                display: inline-block;
                padding: 0px 20px;
                height: 30px;
                line-height: 30px;
                z-index: 1;
                color: blue;
                text-transform: uppercase;
                text-decoration: none;
            }
            .tabs-heading a.active{
                height: 30px;
                border: solid 1px gray;
                border-bottom: none;
                background-color: #FFF;
            }
            .tabs-content{
                border: solid 1px gray;
                border-top: none;
                min-height: 200px;
                padding: 10px;
            }
             
        </style>
    </head>
    <body ng-app="myApp" ng-controller="TabController">
        <div class="tabs-heading">
            <a href="#" ng-class="{active:isActiveTab(1)}" ng-click="changeTab(1)">Tab 1</a>
            <a href="#" ng-class="{active:isActiveTab(2)}" ng-click="changeTab(2)">Tab 2</a>
            <a href="#" ng-class="{active:isActiveTab(3)}" ng-click="changeTab(3)">Tab 3</a>
        </div>
        <div class="tabs-content"  >
            <div ng-show="current_tab == 1" >
                <h1>Nội dung của tab 1</h1>
				 {$ 1 + 2 $}
              <form action=""  method="post" name="form">
			     {% csrf_token %}
                 <div class="f_tim" >
                      <label for = "id_ten"> ten </label>
                       <input type ="text" cols="100" id="id_ten" name ="ten" rows="50" ng-model="congtac.ten"></input>
                 <span class="btn_tim">
                       <button class="lb_btn_tim" ng-click="submit($event)"> tim kiem </button>
                 </span>
                 </div><!-- /input-group -->
              </form>
          
				{% render_table table_ketqua %}
            </div>
            <div ng-show="current_tab == 2">
                <h1>Nội dung của tab 2</h1>
            </div>
            <div  ng-show="current_tab == 3">
                <h1>Nội dung của tab 3</h1>
            </div>
        </div>
    </body>
</html>

phuthuproject/apps/chuyenthue/templates/danhsach.html
{% load static %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

 <html>
     <head>
         <title> Danh sách phiếu chuyển</title>
         <meta http-equiv="Content-Type" content="text/html" meta charset=utf-8">
    	<script language="javascript" src="{% static  "djng/js/angular.min.js" %}"> </script>
        <script language="javascript" src="{% static  "djng/app_congtac.js" %}"></script>
     </head>
     <body>


               <table class="qh-td">
                        <tr>
                            <td id="quochieu1">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM </td>
                        </tr>
                </table>
                <table class="qh-td">
                        <tr>
                            <td id="quochieu2">
                                <u>Độc lập - Tự do - Hạnh phúc </u>
                            </td>
                        </tr>
                </table>

                <table class="qh-td">
                        <tr>
                            <td id="tieude">
                                <br>DANH SÁCH PHIẾU CHUYỂN THÔNG TIN  <br> ĐỊA CHÍNH ĐỂ XÁC ĐỊNH NGHĨA VỤ TÀI CHÍNH
                                <hr id="hang2">
                                <br>
                            </td>

                        </tr>
                </table>
                <table class="bang">
                        <tr>
                            <td id="stt" ><b>STT</b> </td>
                            <td id="hvt"  ><b>Họ và tên</b> </td>
                            <td id="dc"  > <b>Địa chỉ đất</b></td>
                            <td id="s" > <b>Số PC </b></td>
                        </tr>
                </table>
{% regroup data_row by ngaychuyen as so_list %}
             {% for so in so_list %}

            {% with forloop.counter as stt %}
               {% for s in so.list %}

                <table class="bang">
                        <tr>
                            <td id="sothutu" ><b style="color: blue;"> {{ stt }}</b></td>
                            <td id="hovaten" style="color:blue; "> <b>{% if not s.hovaten is null %} {{ s.hovaten }} {% endif %} </b> </td>
                            <td id="diachi" ><b style="color: blue;">{% if not s.dcthuadat is null %} {{ s.dcthuadat }} {% endif %} </b></td>
                            <td id="soin" ><b style="color: blue;">{% if not s.soin is null %} {{ s.soin }} {% endif %} </b></td>

                        </tr>
                </table>

              {% endfor %}
            {% endwith %}
        {% endfor %}
         <br>
         <table>
                        <tr>
                            <td id="ngay" ><b> Cái Răng, ngày {% now "d" %} tháng {% now "m" %} năm {% now "Y" %} </b></td>
                        </tr>

         </table>

         <table>
                        <tr>
                            <td id="nguoigiao" ><b>Người giao</b></td>
                            <td id="nguoinhan"><b>Người nhận</b></td>
                        </tr>
         </table>

   </body>

</html>

phuthuproject/apps/chuyenthue/templates/detail.html
{% extends "admin/base_site.html" %}
{% load static %}
{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static "css/admin.
css" %}" />
{% endblock %}
{% block title %}
Order {{ order.id }} {{ block.super }}
{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url "admin:index" %}">Home</a> &rsaquo;
<a href="{% url "admin:orders_order_changelist" %}">Orders</a> 
&rsaquo;
<a href="{% url "admin:orders_order_change" order.id %}">Order {{ 
order.id }}</a>
&rsaquo; Detail
</div>
{% endblock %}
{% block content %}
<h1>Order {{ order.id }}</h1>
<ul class="object-tools">
<li>
<a href="#" onclick="window.print();">Print order</a>
</li>
</ul>
<table>
<tr>
<th>Created</th>
<td>{{ order.created }}</td>
</tr>
<tr>
<th>Customer</th>
<td>{{ order.first_name }} {{ order.last_name }}</td>
</tr>
<tr>
<th>E-mail</th>
<td><a href="mailto:{{ order.email }}">{{ order.email }}</a></td>
</tr>
<tr>
<th>Address</th>
<td>{{ order.address }}, {{ order.postal_code }} {{ order.city 
}}</td>
</tr>
<tr>
<th>Total amount</th>
<td>${{ order.get_total_cost }}</td>
</tr>
<tr>
<th>Status</th>
<td>{% if order.paid %}Paid{% else %}Pending payment{% endif %}</
td>
</tr>
</table>
<div class="module">
<div class="tabular inline-related last-related">
<table>
<h2>Items bought</h2>
<thead>
<tr>
<th>Product</th>
<th>Price</th>
<th>Quantity</th>
<th>Total</th>
</tr>
</thead>
<tbody>
{% for item in order.items.all %}
<tr class="row{% cycle "1" "2" %}">
<td>{{ item.product.name }}</td>
<td class="num">${{ item.price }}</td>
<td class="num">{{ item.quantity }}</td>
<td class="num">${{ item.get_cost }}</td>
</tr>
{% endfor %}
<tr class="total">
<td colspan="3">Total</td>
<td class="num">${{ order.get_total_cost }}</td>
</tr>
</tbody>
</table>
</div>
</div>
{% endblock %}

phuthuproject/apps/chuyenthue/templates/mytemplate.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>My Title</title>
        <style type="text/css">
            @page {
                size: {{ pagesize }};
                margin: 1cm;
                @frame footer {
                    -pdf-frame-content: footerContent;
                    bottom: 0cm;
                    margin-left: 9cm;
                    margin-right: 9cm;
                    height: 1cm;
                }
            }
        </style>
    </head>
    <body>
        <div>
            {% for item in mylist %}
                RENDER MY CONTENT
            {% endfor %}
        </div>
        <div id="footerContent">
            {%block page_foot%}
                Page <pdf:pagenumber>
            {%endblock%}
        </div>
    </body>
</html>

phuthuproject/apps/chuyenthue/templates/pdf.html
<html>
<body>
<h1>My Shop</h1>
<p>
Invoice no. {{ tpc.id }}</br>
<span class="secondary">
{{ tpc.created|date:"M d, Y" }}
</span>
</p>
<h3>Bill to</h3>
<p>
{{ tpc.hovaten }} {{ tpc.diachi }}<br>
{{ tpc.ngaychuyen }}<br>
{{ tpc.so }}<br>
{{ tpc.thuadatso }}, {{ tpc.tobando }}
</p>
<h3>Items bought</h3>
<table>
<thead>
<tr>
<th>Product</th>
<th>Price</th>
<th>Quantity</th>
<th>Cost</th>
</tr>
</thead>
<tbody>
{% for item in tpc.items.all %}
<tr class="row{% cycle "1" "2" %}">
<td>{{ item.product.name }}</td>
<td class="num">${{ item.price }}</td>
<td class="num">{{ item.quantity }}</td>
<td class="num">${{ item.get_cost }}</td>
</tr>
{% endfor %}
<tr class="total">
<td colspan="3">Total</td>
<td class="num">${{ tpc.get_total_cost }}</td>
</tr>
</tbody>
</table>
<span class="{% if tpc.paid %}paid{% else %}pending{% endif %}">
{% if tpc.paid %}Paid{% else %}Pending payment{% endif %}
</span>
</body>
</html>

phuthuproject/apps/chuyenthue/templates/select_file.html
<form action="" method="post">{% csrf_token %}
    {{ form }}

    <ul>{{ items|unordered_list }}</ul>
    <input type="hidden" name="action" value="select_file_action" />
    <input type="submit" name="apply" value="Save" />
</form>

phuthuproject/apps/myapp/templates/invoice.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
 <html>
     <head>
         <title>Title</title>
         <style type="text/css">
             body {
                 font-weight: 200;
                 font-size: 14px;
             }
             .header {
                 font-size: 20px;
                 font-weight: 100;
                 text-align: center;
                 color: #007cae;
             }
             .title {
                 font-size: 22px;
                 font-weight: 100;
                /* text-align: right;*/
                padding: 10px 20px 0px 20px;
             }
             .title span {
                 color: #007cae;
             }
             .details {
                 padding: 10px 20px 0px 20px;
                 text-align: left !important;
                 /*margin-left: 40%;*/
             }
             .hrItem {
                 border: none;
                 height: 1px;
                 /* Set the hr color */
                 color: #333; /* old IE */
                 background-color: #fff; /* Modern Browsers */
             }
         </style>
     </head>
     <body>
         <div class='wrapper'>
             <div class='header'>
                 <p class='title'>Invoice # {{ order_id}}</p>
             </div>
         <div>
         <div class='details'>
             Bill to:{{ customer_name}} <br/>
             Amount: {{ amount}} <br/>
             Date:{{ today }}
             <hr class='hrItem' />
         </div>
     </div>
     </body>
 </html>

phuthuproject/apps/myapp/templates/ketqua_tim_congtac.html
{# ketqua_tim_congtac.html #}
{% extends "main.html" %}
{% load render_table from django_tables2 %}
{% load staticfiles %}
<!doctype html>
{% block content %}
<html>
    <head>
        <!--link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" /-->
		<link href="{% static 'css/screen.css' %}" rel="stylesheet" media="screen"/>
    </head>
    <body>
        <div id ="ketquatimkiem" >
		   {% render_table table_ketqua %}
		</div>
    </body>
</html>
{% endblock %}

phuthuproject/apps/myapp/templates/nhap_congtac.html
{% extends "main.html" %}


{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Hoc AngularJS </title>

    <link href="{% static 'css/congtac.css' %}" rel="stylesheet" media="screen">
	<meta http-equiv= "Content-type" content="text/html"; charset="UTF-8">
	<!--script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.28/angular.min.js"></script-->
	<script language="javascript" src="{% static  "djng/js/angular.min.js" %}"> </script>
    <script language="javascript" src="{% static  "djng/app_congtac.js" %}"></script>
</head>


<body  ng-app="myApp">

<section  ng-controller="PanelController as panel">
    <ul class="nav nav-pills">
        <li ng-class="{active: panel.isSelected(1)}">
            <a href ng-click="panel.selectTab(1)"> Trang 1 </a>
        </li>
        <li ng-class="{active: panel.isSelected(2)}">
            <a href ng-click="panel.selectTab(2)"> Trang 2 </a>
        </li>
        <li ng-class="{active: panel.isSelected(3)}">
            <a href ng-click="panel.selectTab(3)"> Trang 3 </a>
        </li>
    </ul>
    <div class = "panel" ng-show="panel.isSelected(1)">
         <h4> {$ 3 -  2 $} </h4>

    </div>
    <div class="panel" ng-show="panel.isSelected(2)">
         <h4> {$ 1 + 1 $} </h4>
          <blockquote>  </blockquote>
    </div>
    <div class="panel" ng-show="panel.isSelected(3)">
              <form name="form"  ng-controller="MyFormCtrl" method= "post" > {% csrf_token %}
                  
				  <label for="id_id">id</label>
                        <input type ="text" cols="40" id="id_id" name="id" rows="10" ng-model="congtac.id"></input>
				  <label for="id_ten">ten</label>
                        <input type ="text" cols="40" id="id_ten" name="ten" rows="10" ng-model="congtac.ten"></input>
                  <label for="id_diachi">diachi</label>
                        <input type="text" cols="40" id="id_diachi" name="diachi" rows="10" ng-model="congtac.diachi"></input>

                  <p><label for="id_congtac">Loai:</label>
                      <select ng-model="congtac.congtac" id="id_congtac" name="congtac">
                             <option value="" selected="selected">---------</option>
                             <option value="1">Backlog</option>
                             <option value="2">Done</option>
                             <option value="3">In progress</option>
                      </select>
                      <button ng-click="submit($event)"> Submit </button>
                  </p>
              </form>
          <h4> {$ 1 + 2 $} </h4>
    </div>
</section>
</body>
</html>
{% endblock %}

phuthuproject/apps/myapp/templates/thu.html
{% load render_table from django_tables2 %}
{% load static %}
<!doctype html>
<html lang="vi">
    <head>
        <meta charset="UTF-8">
        <title>Ví dụ Tabs trong AngularJS - Freetuts.net</title>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.min.js"></script>
          <link href="{% static 'css/timkiem.css' %}" rel="stylesheet" media="screen"/>
		 <link href="{% static 'css/forms.css' %}" rel="stylesheet" media="screen">
         <link href="{% static 'css/screen.css' %}" rel="stylesheet" media="screen"/>
         <link href="{% static 'css/thu.css' %}" rel="stylesheet" media="screen"/>
	     <meta http-equiv= "Content-type" content="text/html"; charset="UTF-8">

        <script language="javascript" src="{% static  "djng/js/angular.min.js" %}"> </script>

        <script language="javascript" src="{% static  "djng/thu.js" %}"></script>
		
		<style>
            *{margin:0;padding:0}
            body{margin:20px;}
            .tabs-heading{
                padding: 20px 20px 0px 20px;
                height: 30px;
                border: solid 1px gray;
                border-radius: 5px 5px 0px 0px;
                background-color: #cae8fd;
            }
            .tabs-heading a{
                display: inline-block;
                padding: 0px 20px;
                height: 30px;
                line-height: 30px;
                z-index: 1;
                color: blue;
                text-transform: uppercase;
                text-decoration: none;
            }
            .tabs-heading a.active{
                height: 30px;
                border: solid 1px gray;
                border-bottom: none;
                background-color: #FFF;
            }
            .tabs-content{
                border: solid 1px gray;
                border-top: none;
                min-height: 200px;
                padding: 10px;
            }
             
        </style>
    </head>
    <body ng-app="myApp" ng-controller="TabController">
        <div class="tabs-heading">
            <a href="#" ng-class="{active:isActiveTab(1)}" ng-click="changeTab(1)">Tab 1</a>
            <a href="#" ng-class="{active:isActiveTab(2)}" ng-click="changeTab(2)">Tab 2</a>
            <a href="#" ng-class="{active:isActiveTab(3)}" ng-click="changeTab(3)">Tab 3</a>
        </div>
        <div class="tabs-content"  >
            <div ng-show="current_tab == 1" >
                <h1>Nội dung của tab 1</h1>
				 {$ 1 + 2 $}
              <form action=""  method="post" name="form">
			     {% csrf_token %}
                 <div class="f_tim" >
                      <label for = "id_ten"> ten </label>
                       <input type ="text" cols="100" id="id_ten" name ="ten" rows="50" ng-model="congtac.ten"></input>
                 <span class="btn_tim">
                       <button class="lb_btn_tim" ng-click="submit($event)"> tim kiem </button>
                 </span>
                 </div><!-- /input-group -->
              </form>
          
				{% render_table table_ketqua %}
            </div>
            <div ng-show="current_tab == 2">
                <h1>Nội dung của tab 2</h1>
            </div>
            <div  ng-show="current_tab == 3">
                <h1>Nội dung của tab 3</h1>
            </div>
        </div>
    </body>
</html>

phuthuproject/apps/myapp/templates/tim_congtac_thanhcong.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ket qua nhap thanh cong </title>
</head>
<body>
<h1>chuyen thue created thanh cong </h1>
<ul>
    <li>
        <a href="{% url 'chuyenthue:nhap' %}">Back to nhap</a>
    </li>
</ul>

</body>
</html>